name: alpha_estates
description: 30 days of flutter development
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0-417.1.beta <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  eva_icons_flutter: ^3.1.0
  google_fonts: ^4.0.4
  otp_text_field: ^1.1.3
  google_maps_flutter: ^2.2.5
  http: ^0.13.5
  fluttertoast: ^8.2.1
  toast: ^0.3.0
  url_launcher: ^6.1.10
  anim_search_bar: ^2.0.3
  firebase_auth: ^4.4.2
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  get: ^4.6.5

flutter_launcher_icons:
  image_path: "icons/AppIcon.png"
  android: true
  ios: true
  min_sdk_android : 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - icons/
    - images/
    - logo/
  fonts:
    - family: LeonSans
      fonts:
        - asset: fonts/LeonSans-Regular.otf
          weight: 400
        - asset: fonts/LeonSans-Medium.otf
          weight: 500
        - asset: fonts/LeonSans-Bold.otf
          weight: 700
        - asset: fonts/Roboto-Medium.ttf
        - asset: fonts/Roboto-Bold.ttf
        - asset: fonts/Roboto-Regular.ttf
  
  
  
